# Generated by Django 2.2.3 on 2019-08-31 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190831_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='UserAgent',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlog',
            name='ipLog',
            field=models.CharField(max_length=32),
        ),
    ]
